### ISSUE TITLE
QUESTION: How to implement a working typescript transformer?

### ISSUE THREAD

**Issue by timidak** [atSCM/tutorial-custom-transformer#7]
I'm not really sure about this but, I tried to get a TypeScript transformer working today and it didn't really work out well.
I know that the API has changed a bit, but I'm not really getting to a point where it works out, do you mind helping me with a little example custom Transformer or could you help me fixing mine?

```typescript
import { Buffer } from 'buffer';
import { PartialTransformer } from 'atscm';
import { transform } from '@babel/core';

export default class BabelTransformer extends PartialTransformer {
  static shouldBeTransformed(file) {
    return file.extname === '.ts';
  }

  transformFromFilesystem(node, context) {
    const { code } = transform(node.file.contents, {
      filename: node.file.name, // I acutally need to specify a name when using transform 
      presets: ['@babel/preset-typescript']
    });

    // Create new file with ES5 content
    const result = node.file.clone(); // ?
    result.contents = Buffer.from(code); // Error: cannot read 'contents' of undefined, so I guess node.file.clone() doesn't work

    // We're done, pass the new file to other streams
    context(null, result);
  }
}
```

I would really appreciate any help 😄

**Comment by timidak** [comment]
ping @LukasHechenberger

**Comment by LukasHechenberger** [comment]
Hi! I will look into this, thanks for reporting!

**Comment by LukasHechenberger** [comment]
It turned out that the Serverscript- and DisplayTransformers needed a patch before I got this to work... (See https://github.com/atSCM/atscm/pull/406)

I also set up a demo project, you may want to have a look: https://github.com/atSCM/ts-demo 😀

The transformer itself looks like this:

```js
const { extname } = require('path');
const { PartialTransformer } = require('atscm');
const { transform } = require('@babel/core');

module.exports = class TypeScriptTransformer extends PartialTransformer {
  shouldBeTransformed(file) {
    return extname(file.fileName) === '.ts';
  }

  async transformFromFilesystem(node) {
    if (!this.shouldBeTransformed(node)) return;

    const { code } = transform(node.stringValue, {
      filename: node.fileName, // I acutally need to specify a name when using transform
      presets: ['@babel/preset-typescript'],
    });

    node.setRawValue(Buffer.from(code));
  }
};
```

It's not perfect, but I'll continue to work on better TypeScript support. Thanks for you input, please close this issue if this command and ts-demo's readme answers your question.

**Comment by LukasHechenberger** [comment]
FYI: Better TypeScript support is tracked in https://github.com/atSCM/atscm/issues/407
